# Generated by Django 4.2.24 on 2025-10-13 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0001_initial'),
        ('schoolManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='management',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_management', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exammanagement',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to='student.courses'),
        ),
        migrations.AddField(
            model_name='exammanagement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_examManagement', to='student.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_announcement', to='schoolManagement.management'),
        ),
        migrations.AlterUniqueTogether(
            name='exammanagement',
            unique_together={('student', 'course')},
        ),
    ]
