# Generated by Django 4.2.24 on 2025-10-10 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_department'),
        ('schoolManagement', '0007_rename_details_announcement_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_semester_test_marks', models.CharField(blank=True, max_length=20)),
                ('first_semester_exam_marks', models.CharField(blank=True, max_length=20)),
                ('second_semester_test_marks', models.CharField(blank=True, max_length=20)),
                ('second_semester_exam_marks', models.CharField(blank=True, max_length=20)),
                ('third_semester_test_marks', models.CharField(blank=True, max_length=20)),
                ('third_semester_exam_marks', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_courses', to='student.courses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_examManagement', to='student.student')),
            ],
        ),
    ]
