# Generated by Django 4.2.24 on 2025-10-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolManagement', '0008_exammanagement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='DOB',
            field=models.DateField(blank=True, max_length=30),
        ),
    ]
