# Generated by Django 4.2.24 on 2025-10-11 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_department'),
        ('schoolManagement', '0011_alter_management_dob'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exammanagement',
            unique_together={('student', 'course')},
        ),
    ]
