# Generated by Django 4.2.24 on 2025-10-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default=True, max_length=30),
        ),
    ]
