# Generated by Django 5.2.6 on 2025-10-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='semester',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='courses',
            name='year',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
