# Generated by Django 5.2.6 on 2025-10-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_courses_semester_courses_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='students',
            field=models.ManyToManyField(related_name='courses', to='student.student'),
        ),
    ]
